name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - working-directory: ./firstPractice
      - uses: actions/checkout@v2
      - uses: bazelbuild/setup-bazelisk@v2
      - run: bazel build //...
      - run: bazel test //...
