packages:
  # Include all directories in the workspace
  - '*'
  # Include all subdirectories at any depth
  - '**/*'
  # Exclude node_modules folders anywhere in the tree
  - '!**/node_modules/**'
  # Exclude node_modules folder in root
  - '!node_modules'
  # Exclude anything inside bazel dirs
  - '!bazel-*/**'
